### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by thenovacreator** [lehuizi/hcloud-failover-keepalived#2]
Hello guys,

i found this plugin and get it working partial. Any i got some questions.

What are the first two script arguments for? I see that the last is for the desired state. But the first two do not seem to be used as i was looking at the script.

And could please provide a config example?  Right now i am using the script with a command line put into a sh file used in the notify_master. Seems a little bit to complicated and incomplete. Where should be something for the fault state right?

If you d like i could put some things together in the readme if the setup runs. Would you then mind to accept a pull request?

**Comment by lehuizi** [comment]
Hey,

the first two arguments exist because of keepalived itself. It automatically delivers the following states to the script:

$1 = "GROUP" or "INSTANCE"
$2 = name of group or instance
$3 = target state of transition ("MASTER", "BACKUP", "FAULT")

We just use the third var and don‘t need the other ones.

I will take a look at my iwn config later today and send you an example.

Pull requests are always welcome!

**Comment by thenovacreator** [comment]
Okay then i assume keealived can call the script directly and there does need to be a routing script. But how is it included?

**Comment by lehuizi** [comment]
This is my keepalived config:


```
vrrp_script chk_load_balancer {
  script "pidof haproxy"
  interval 2
}

vrrp_instance VI_1 {
  interface tun0
  state MASTER
  priority 200

  virtual_router_id 33

  authentication {
    auth_type PASS
    auth_pass secretpasswordhere
  }

  notify /etc/keepalived/hcloud-failover/hcloud_failover.py
}
```

**Comment by satybald** [comment]
@lehuizi don't you need to specify `virtual_ipaddress` section in keepalived?

**Comment by lehuizi** [comment]
No, the script is adding regarded IP adresses but maybe it‘s an option for the future.
